# Generated by Django 5.2.17 on 2026-09-17 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('goods', '0027_category_multilang_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlatformDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('search_volume', models.PositiveIntegerField(default=0, verbose_name='搜索量')),
                ('click_volume', models.PositiveIntegerField(default=0, verbose_name='点击量')),
                ('order_volume', models.PositiveIntegerField(default=0, verbose_name='订单量')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='转化率(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '平台每日指标',
                'verbose_name_plural': '平台每日指标',
                'db_table': 'ads_platform_daily_metric',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdProductDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('search_volume', models.PositiveIntegerField(default=0, verbose_name='搜索量')),
                ('click_volume', models.PositiveIntegerField(default=0, verbose_name='点击量')),
                ('order_volume', models.PositiveIntegerField(default=0, verbose_name='订单量')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='转化率(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品每日指标',
                'verbose_name_plural': '商品每日指标',
                'db_table': 'ads_product_daily_metric',
                'ordering': ['-date'],
            },
        ),
        migrations.RenameIndex(
            model_name='adcampaignrecord',
            new_name='ads_campaig_spu_id_990c64_idx',
            old_name='ads_campaig_spu_id_6f6e6c_idx',
        ),
        migrations.RenameIndex(
            model_name='adcampaignrecord',
            new_name='ads_campaig_platfor_828a59_idx',
            old_name='ads_campaig_platfor_1f2b53_idx',
        ),
        migrations.AddField(
            model_name='adplatformdailymetric',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='ads.adplatform', verbose_name='投放平台'),
        ),
        migrations.AddField(
            model_name='adproductdailymetric',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_daily_metrics', to='ads.adplatform', verbose_name='投放平台'),
        ),
        migrations.AddField(
            model_name='adproductdailymetric',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_daily_metrics', to='goods.spu', verbose_name='商品'),
        ),
        migrations.AlterUniqueTogether(
            name='adplatformdailymetric',
            unique_together={('platform', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='adproductdailymetric',
            unique_together={('platform', 'spu', 'date')},
        ),
    ]
