# Generated by Django 5.2.17 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0022_spu_arabic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='spu',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='商品名称（英语）'),
        ),
        migrations.AddField(
            model_name='spu',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='商品描述（英语）'),
        ),
    ]