# Generated by Django 5.2.17 on 2026-09-12 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_rename_sku_code_to_sku_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryrenameapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='categoryrenameapplication',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryrenameapplication',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='leaderchangeapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='leaderchangeapplication',
            name='group',
        ),
        migrations.RemoveField(
            model_name='leaderchangeapplication',
            name='new_leader',
        ),
        migrations.RemoveField(
            model_name='leaderchangeapplication',
            name='reviewer',
        ),
        migrations.AlterField(
            model_name='sku',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='折扣价（$）'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='售价（$）'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='SKU名称'),
        ),
        migrations.DeleteModel(
            name='BrandRenameApplication',
        ),
        migrations.DeleteModel(
            name='CategoryRenameApplication',
        ),
        migrations.DeleteModel(
            name='LeaderChangeApplication',
        ),
    ]
