# Generated by Django 5.2.17 on 2026-09-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0025_remove_unused_application_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='redis_key',
        ),
    ]
