# Generated by Django 5.2.17 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0026_remove_productmedia_redis_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='分类名称（英语）'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='分类名称（中文）'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='分类名称（阿拉伯语）'),
        ),
    ]