# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0027_category_multilang_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('product', '商品'), ('showcase', '作品展示')], default='product', help_text='product=普通商品分类 / showcase=作品展示（非商品，无价格不售卖）', max_length=20, verbose_name='分类类型'),
        ),
    ]