# Generated by Django 5.2.17 on 2026-09-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_rbac_abac_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('superadmin', '超级管理员'), ('customer', '普通用户')], max_length=32, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('superadmin', '超级管理员'), ('customer', '普通用户')], max_length=32, verbose_name='角色'),
        ),
    ]
