"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from django.utils import timezone
from pathlib import Path
import os
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

if os.getenv("DEL_ENV") != "prod":
    from dotenv import load_dotenv
    load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY environment variable is required. '
        'Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
    )

# SECURITY WARNING: don't run with debug turned on in production!

# ALLOWED_HOSTS will be set in prod.py with a RuntimeError guard
# to prevent missing configuration in production.

DOMAIN = os.getenv('DOMAIN', 'http://127.0.0.1:8090')
APP_VERSION = os.getenv('APP_VERSION', 'dev')
GIT_COMMIT = os.getenv('GIT_COMMIT', 'unknown')
DJANGO_ENV = os.getenv('DJANGO_ENV', 'dev')

# Mock 支付（开发/测试用支付模拟器）安全开关：
# 1. 生产环境（prod）强制禁用，即使显式设置 ENABLE_MOCK_PAYMENT=true 也忽略，
#    防止攻击者通过 Mock 支付端点伪造"已支付"状态。
# 2. 非生产环境默认开启（dev/local），便于本地联调。
_ENABLE_MOCK_REQUESTED = os.getenv(
    'ENABLE_MOCK_PAYMENT',
    'true' if DJANGO_ENV in ('dev', 'local') else 'false',
).lower() == 'true'
ENABLE_MOCK_PAYMENT = _ENABLE_MOCK_REQUESTED and DJANGO_ENV != 'prod'

# Mock 支付签名密钥：必须显式配置独立密钥，绝不回退到 SECRET_KEY。
# 若 SECRET_KEY 泄露，攻击者即可伪造 Mock 支付回调；独立密钥可隔离该风险。
# 非生产环境未配置独立密钥时，禁用 Mock 支付（fail-closed）。
MOCK_PAYMENT_SECRET = os.getenv('MOCK_PAYMENT_SECRET', '')
if ENABLE_MOCK_PAYMENT and not MOCK_PAYMENT_SECRET:
    ENABLE_MOCK_PAYMENT = False
TURNSTILE_SECRET_KEY = os.getenv('TURNSTILE_SECRET_KEY', '')
TURNSTILE_VERIFY_TIMEOUT = float(os.getenv('TURNSTILE_VERIFY_TIMEOUT', '3.0'))

# 平台与前端相关配置（欢迎邮件 / 验证链接使用）
PLATFORM_NAME = os.getenv('PLATFORM_NAME', 'CarveNex')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://admin.carvenex.com')
SUPPORT_URL = os.getenv('SUPPORT_URL', 'https://carvenex.com/support')
# Application definition

INSTALLED_APPS = [
    'daphne',
    'django_prometheus',
    'corsheaders',  # 与 CorsMiddleware 配套，否则 CORS 配置可能不完整
    'utils',
    # 媒体回退存储（断网/R2 不可达时把媒体字节落库）
    'apps.media.apps.MediaConfig',
    # rbac 是全站基础设施：业务 app 单向依赖它，故排在业务 app 之前
    'apps.rbac.apps.RbacConfig',
    'apps.users.apps.UsersConfig',
    'apps.goods.apps.GoodsConfig',
    'apps.cart.apps.CartConfig',
    'apps.order.apps.OrderConfig',
    'apps.address.apps.AddressConfig',
    'apps.payment.apps.PaymentConfig',
    'apps.review.apps.ReviewConfig',
    'apps.support.apps.SupportConfig',
    'apps.customer_service.apps.CustomerServiceConfig',
    'apps.notification.apps.NotificationConfig',
    'apps.promotion.apps.PromotionConfig',
    'apps.lovegoods.apps.LovegoodsConfig',
    'apps.tracking.apps.TrackingConfig',
    'apps.logistics.apps.LogisticsConfig',
    'apps.ads.apps.AdsConfig',
    'apps.health',
    'channels',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'utils.ip_whitelist_middleware.AdminIpWhitelistMiddleware',  # 管理后台 IP 白名单（ADMIN_IP_WHITELIST 配置，未配置则放行）
    'utils.cookie_domain_middleware.DynamicCookieDomainMiddleware',  # 按请求 Host 动态设定 Cookie Domain（localhost 去 Domain，否则 -.carvenex.com）
    'middleware.memory_watchdog.MemoryWatchdogMiddleware',  # 2C4G：RSS>85% 自保护（清 L1 缓存 + 回收空闲连接）
    'utils.exception_middleware.CustomExceptionMiddleware',
    'middleware.api_version.APIVersionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'utils.csp_middleware.CSPMiddleware',  # API JSON 响应强制严格 CSP（纵深防御 MIME 嗅探/点击劫持），HTML 响应不受影响
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'middleware.jwt_blacklist.JWTBlacklistMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'utils.operation_log_middleware.OperationLogMiddleware',  # 操作日志：按用户类型/日期 层级存储
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

API_V1_SUNSET = os.getenv('API_V1_SUNSET', 'Wed, 30 Sep 2026 23:59:59 GMT')

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '../templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'
ASGI_APPLICATION = 'project.asgi.application'

# ── Django Channels 配置 ──
# 关键：REST 由 gunicorn 处理、WebSocket 由 daphne 处理，二者是不同进程。
# 进程内 InMemoryChannelLayer 无法跨进程广播，导致「客服发消息 → 买家 WS 收不到实时推送」。
# 实时通道：使用进程内内存通道层（无需外部消息中间件）。
# InMemoryChannelLayer 支持单进程上的 Channels（含测试），单机部署无需外部中间件。
# 多 worker 水平扩展时实时推送仅对直连该进程的连接生效；
# 前端已实现「断线自动重连 + 轮询兜底」，WebSocket 不可用时功能仍可用。
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 2C4G：dj-db-conn-pool 提供 MySQL 连接池（MAX_CONNS 上限），防止连接泄漏/打满；
        # 配合 DJANGO_DB_DRIVER=pymysql（纯 Python 驱动）兼容 gevent 协程调度。
        'ENGINE': os.getenv('DB_ENGINE', 'dj_db_conn_pool.backends.mysql'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'CONN_MAX_AGE': 60,  # 60 秒连接复用（无连接池模式下缩短保持时间，避免并发连接堆积打满 MySQL）
        'CONN_HEALTH_CHECKS': True,  # 每次使用前检查连接健康
        'POOL_OPTIONS': {
            'MAX_CONNS': 15,  # 2C4G：单进程连接池上限 ≤15，防连接泄漏耗内存
            'RECYCLE_SEC': 300,  # 5 分钟回收空闲连接
        },
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 3,  # 连接超时 3s
            'read_timeout': 10,  # 查询超时 10s，防止慢查询阻塞
            'write_timeout': 10,  # 写入超时 10s
            # 生产保持 FK 检查开启；仅超时会话参数（测试环境可在 local.py 覆盖）
            'init_command': "SET SESSION wait_timeout=300, SESSION interactive_timeout=300",
        },
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_unicode_ci',
            'SERIALIZE': False,  # 跳过数据序列化（部分 app 表缺失导致 serializing 崩溃）
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# ============================================================
# 文件存储配置（Django 4.2+ STORAGES）
# 未来扩展：只需将 backend 改为 storages.backends.s3boto3.S3Boto3Storage
# 即可接入阿里云 OSS，无需修改任何业务代码
# ============================================================
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8090",
    "http://localhost:8091",
    "http://127.0.0.1:8090",
    "http://127.0.0.1:8091",
]

# django-cors-headers 默认允许头 + 退款幂等键头（Idempotency-Key）
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-request-id',
    'x-requested-with',
    'idempotency-key',
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'America/New_York'

SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.getenv('STATIC_ROOT', os.path.join(BASE_DIR, 'static'))

# 静默 MySQL 不支持的约束警告
SILENCED_SYSTEM_CHECKS = ['models.W036']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'utils.api_jwt_authentication.UsersJWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': () if os.getenv('THROTTLE_DISABLED', '').lower() in ('1', 'true', 'yes') else (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    # 限流速率可被环境变量 THROTTLE_RATES 覆写（JSON，测试/压测放开限流时设大值）。
    # 注意：不要设为 {} 空对象——AnonRateThrottle/UserRateThrottle 取不到 scope 速率
    # 会抛 ImproperlyConfigured("No default throttle rate set ...")，导致所有请求 500。
    # 开发/调试期可设 THROTTLE_DISABLED=1 完全跳过默认节流（仅作用于 DEFAULT_THROTTLE_CLASSES，
    # 视图层 throttle_classes=[] 会被 DRF 替换为空，搜索/支付等专项 scope 仍生效），
    # 生产环境严禁开启。
    'DEFAULT_THROTTLE_RATES': json.loads(os.getenv('THROTTLE_RATES', json.dumps({
        # anon：匿名 IP 维度。1000/小时 ≈ 16 次/分钟，是常见 SPA 页面接口量的合理上限。
        # 公开展示页基类 PublicApiView 已显式 throttle_classes=() 跳过本限流，
        # 此处主要约束"非公开但需登录之前"的探测/握手接口。
        'anon': '1000/hour',
        'user': '5000/hour',
        'admin_login': '5/minute',
        'admin_write': '60/minute',
        'admin_batch': '10/minute',
        # 支付接口专门限流（防刷单 / 防 DoS）
        'payment_create': '30/minute',   # 发起支付：单用户每分钟最多 30 次
        'payment_mock': '10/minute',     # Mock 支付模拟器：单用户每分钟最多 10 次
        'payment_webhook': '300/minute', # 网关回调：公开接口，防 DoS 但需容纳真实回调
    }))),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # 2C4G：默认 20 条/页，最大 100 条/页（上限防一次拉爆单 worker 内存）
    "DEFAULT_PAGINATION_CLASS": "utils.pagination.CappedPageNumberPagination",
    "PAGE_SIZE": 20,  # 每页 20 条数据
    "EXCEPTION_HANDLER": "utils.api_exception.custom_exception_handler",
}

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'CarveNex 商城 API',
    'DESCRIPTION': (
        'CarveNex 精选综合商城接口文档。浏览器第一方会话使用 HttpOnly Cookie 与 CSRF；'
        'Apifox、移动端和服务端客户端使用 Bearer JWT；后台管理接口使用独立 Admin Token。'
    ),
    'VERSION': '1.0.0',
    'OAS_VERSION': '3.1.0',
    'DEFAULT_GENERATOR_CLASS': 'project.openapi.CarveNexSchemaGenerator',
    # 必须显式声明：留空时 drf-spectacular 会「自动推导」URL 公共前缀，
    # 而推导结果随运行环境加载到的 URL 集合而变（pytest 剥到 /api/v1 → tag=address；
    # 独立脚本只剥到 /api → tag=v1），会导致同一份代码生成出两份不同的 Schema，
    # 契约测试与 update_contract_baseline.py 互相打架。固定后 tag 稳定为模块名。
    'SCHEMA_PATH_PREFIX': '/api/v[0-9]',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'DISABLE_ERRORS_AND_WARNINGS': False,
    'AUTHENTICATION_WHITELIST': [
        'utils.api_jwt_authentication.UsersJWTAuthentication',
        'apps.users.session_auth.CookieJWTAuthentication',
        'utils.admin_authentication.ExpiringTokenAuthentication',
    ],
    'POSTPROCESSING_HOOKS': ['project.openapi.postprocess_zh_cn_schema'],
    # 本地化 Swagger UI 资源，避免 CDN 被 CSP / Tracking Prevention 拦截
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True
    },
}

# ── 仅 MySQL：缓存/会话走数据库表 ──
# 验证码/限流/黑名单/会话等共用 django_cache 表（启动时 create_dbc_table）。
# 缓存表会随数据库迁移/启动自动创建，无需额外进程，纯离线自托管可用。
_CACHE_TABLE = 'django_cache_table'
_CACHE_KEY_PREFIX = f"carvenex:{os.getenv('DJANGO_ENV', 'dev')}"


def _db_cache(*, timeout=300):
    """MySQL 后端缓存。所有缓存别名共用一张 django_cache 表；
    保留 rw_default / rw_default_slave 别名以兼容 utils.cache 的读写分离接口（实际读写同库）。
    """
    return {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': _CACHE_TABLE,
        'TIMEOUT': timeout,
        'KEY_PREFIX': _CACHE_KEY_PREFIX,
        # 签名 & 值走 DB 校验（默认 40 字符哈希），转换到 DB 不影响使用
        'VERSION': 1,
    }


CACHES = {
    # 统一使用 Django 官方 DB 缓存（MySQL）
    'default': _db_cache(),
    'rw_default': _db_cache(),
    'rw_default_slave': _db_cache(),
    'session': _db_cache(timeout=86400),
    'verification_code': _db_cache(timeout=600),
    # 进程内 LocMem 近缓存（商品详情/分类树等读多写少数据），
    # 命中即省一次 MySQL 往返；TTL 较短（见 utils/cache.py 两级读取）。
    'local': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'carvenex-local',
        'TIMEOUT': 600,
    },
}

SESSION_ENGINE = "django.contrib.sessions.backends.db"  # 会话直接落 MySQL（无缓存别名耦合）
# SESSION_CACHE_ALIAS 已移除：DB 会话后端不必转缓存 --> 依赖方回退到 SESSION_ENGINE 默认

# ==================== 用户模块可扩展配置 ====================
# 后续调优只需改此处，无需改动业务代码
USERS_SETTINGS = {
    # 用户名
    'USERNAME_MIN_LENGTH': 3,
    'USERNAME_MAX_LENGTH': 15,
    # 密码 —— 须包含大小写字母和数字（OWASP 推荐 ≥ 8 位）
    'PASSWORD_MIN_LENGTH': 8,
    'PASSWORD_MAX_LENGTH': 25,
    'PASSWORD_REQUIRE_UPPER': True,
    'PASSWORD_REQUIRE_LOWER': True,
    'PASSWORD_REQUIRE_DIGIT': True,
    # 图片验证码
    'CAPTCHA_EXPIRE_SECONDS': 120,    # 2 分钟过期
    # 邮箱验证码（统一验证配置）
    'VERIFICATION_CODE_LENGTH': 6,
    'VERIFICATION_CODE_EXPIRE_SECONDS': 300,   # 5 分钟过期
    'VERIFICATION_RATE_LIMIT_SECONDS': 60,     # 60 秒发送间隔
    'VERIFICATION_MAX_ATTEMPTS': 5,     # 每条验证码最多尝试验证次数
    # 全局发送额度（防恶意刷爆发件账号日额度；QQ 邮箱日额度约 50 封，保守留余量）
    'VERIFICATION_GLOBAL_MINUTE_LIMIT': 10,   # 全系统每 60 秒最多发送验证码数
    'VERIFICATION_GLOBAL_DAILY_LIMIT': 200,   # 全系统每 24 小时最多发送验证码数
    # 邮箱验证令牌
    'EMAIL_VERIFICATION_TOKEN_EXPIRE_MINUTES': 15,  # 验证令牌有效期
    # 邮箱验证码（独立流程）
    'VERIFICATION_CODE_EXPIRE': 600,  # 10 分钟过期
    # 用户名修改冷却期
    'USERNAME_CHANGE_COOLDOWN_DAYS': 30,  # 修改用户名后需等待天数
}

# ==================== 邮件 SMTP 配置（QQ邮箱）====================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.qq.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True').lower() == 'true'
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # QQ邮箱授权码
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'CarveNex <noreply@qq.com>')

# =============== 管理后台邮箱（QQ）===============
ADMIN_EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.qq.com')
ADMIN_EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
ADMIN_EMAIL_USE_SSL = True
ADMIN_EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
ADMIN_EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
ADMIN_DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'CarveNex <noreply@qq.com>')

# =============== 用户注册邮箱（独立配置）===============
USER_EMAIL_HOST = os.getenv('USER_EMAIL_HOST', 'smtp.qq.com')
USER_EMAIL_PORT = int(os.getenv('USER_EMAIL_PORT', '465'))
USER_EMAIL_USE_SSL = os.getenv('USER_EMAIL_USE_SSL', 'True').lower() == 'true'
USER_EMAIL_USE_TLS = os.getenv('USER_EMAIL_USE_TLS', 'False').lower() == 'true'
USER_EMAIL_HOST_USER = os.getenv('USER_EMAIL_HOST_USER', '')
USER_EMAIL_HOST_PASSWORD = os.getenv('USER_EMAIL_HOST_PASSWORD', '')
USER_DEFAULT_FROM_EMAIL = os.getenv('USER_DEFAULT_FROM_EMAIL', 'CarveNex <noreply@qq.com>')

# =============== 多发件账号池（额度感知轮换）===============
# 格式（JSON 数组字符串，.env 里配 EMAIL_ACCOUNTS）：
#   [{"host":"smtp.qq.com","port":465,"user":"a@qq.com","password":"授权码",
#     "from_email":"CarveNex <a@qq.com>","use_ssl":true,"daily_limit":500},
#    {"host":"smtp.qq.com","port":465,"user":"b@qq.com","password":"授权码",
#     "from_email":"CarveNex <b@qq.com>","use_ssl":true,"daily_limit":500}]
# 未配置时回退为单一账号（EMAIL_HOST_USER 等，兼容旧配置）。
import json as _json
_EMAIL_ACCOUNTS_RAW = os.getenv('EMAIL_ACCOUNTS', '')
if _EMAIL_ACCOUNTS_RAW:
    try:
        EMAIL_ACCOUNTS = _json.loads(_EMAIL_ACCOUNTS_RAW)
        for _acc in EMAIL_ACCOUNTS:
            _acc.setdefault('port', int(_acc.get('port', 465)))
            _acc.setdefault('use_ssl', True)
            _acc.setdefault('use_tls', False)
            _acc.setdefault('daily_limit', int(_acc.get('daily_limit', 500)))
    except Exception:
        EMAIL_ACCOUNTS = []
else:
    EMAIL_ACCOUNTS = []
if not EMAIL_ACCOUNTS:
    EMAIL_ACCOUNTS = [{
        'host': EMAIL_HOST,
        'port': EMAIL_PORT,
        'user': EMAIL_HOST_USER,
        'password': EMAIL_HOST_PASSWORD,
        'from_email': DEFAULT_FROM_EMAIL,
        'use_ssl': EMAIL_USE_SSL,
        'daily_limit': int(os.getenv('EMAIL_ACCOUNT_DAILY_LIMIT', '500')),
    }]

# Simple JWT settings
SIMPLE_JWT = {
    # 2026-09-19 应用户要求：Token 改为永久有效（100 年 ≈ 永不过期），
    # 便于 Postman/Apifox 等客户端长期持有同一 Token 调试。
    # ⚠️ 安全权衡：永久 Token 一旦泄露将长期有效，仅靠安全戳机制
    #   （改密码/角色变更旋转 security_stamp）兜底失效。
    # 如需恢复原过期策略，改回：ACCESS 15 分钟 / REFRESH 2 小时。
    'ACCESS_TOKEN_LIFETIME': timezone.timedelta(days=36500),  # 访问令牌永久有效（100年）
    'REFRESH_TOKEN_LIFETIME': timezone.timedelta(days=36500),  # 刷新令牌永久有效（100年）
    'ROTATE_REFRESH_TOKENS': True,  # 刷新令牌时自动更新刷新令牌
    'BLACKLIST_AFTER_ROTATION': True,  # 刷新后将旧的刷新令牌加入黑名单
    'UPDATE_LAST_LOGIN': True,  # 更新用户最后登录时间
    'ALGORITHM': 'HS256',  # 使用的加密算法
    'SIGNING_KEY': os.getenv('JWT_SIGNING_KEY') or SECRET_KEY,  # 签名密钥：优先独立 JWT_SIGNING_KEY（与 SECRET_KEY 隔离爆炸半径），未配置时回退 SECRET_KEY
    'VERIFYING_KEY': None,  # 验证密钥，使用对称加密时为None
    'AUTH_HEADER_TYPES': ('Bearer',),  # 认证头类型
    'AUTH_HEADER_NAME': 'Authorization',  # 认证头名称
    'USER_ID_FIELD': 'id',  # 用户模型中用作用户ID的字段
    'USER_ID_CLAIM': 'user_id',  # token中用户ID的声明名称
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',  # JWT ID声明，用于防止重放攻击
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timezone.timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timezone.timedelta(days=1),
}

# 日志配置
LOG_LEVEL = os.getenv('LOG_LEVEL', 'DEBUG')
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
        "app_log": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "logs/app.log",
            "maxBytes": 10_485_760,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "task_log": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "logs/task.log",
            "maxBytes": 10_485_760,
            "backupCount": 3,
            "formatter": "verbose",
        },
        "task_error_log": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "logs/task_error.log",
            "maxBytes": 10_485_760,
            "backupCount": 3,
            "formatter": "verbose",
        },
    },
    "formatters": {
        "verbose": {
            "format": "[{levelname}]::{asctime}::{module}::{message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
        "json": {
            "()": "utils.json_logging.JsonFormatter",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "app_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "app_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG" if os.getenv('LOG_SQL', 'false').lower() == 'true' else "INFO",
            "propagate": False,
        },
        "biz": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# ==================== 客服系统 ====================
# 说明：以下配置控制客服聊天系统的限流、文件上传、搜索等行为

# 客服消息限流：滑动时间窗口大小（秒），配合 CS_RATE_LIMIT_MAX 使用
CS_RATE_LIMIT_WINDOW = 60
# 客服消息限流：每个用户在滑动窗口内最多发送消息数
CS_RATE_LIMIT_MAX = 30
# 客服限流缓存 key 前缀，用于区分不同限流场景
CS_RATE_LIMIT_KEY_PREFIX = 'cs:rate_limit:user'
# 客服图片上传：允许的 MIME 类型集合
CS_ALLOWED_IMAGE_TYPES = {'image/jpeg', 'image/png', 'image/gif'}
# 客服视频上传：允许的 MIME 类型集合
CS_ALLOWED_VIDEO_TYPES = {'video/mp4'}
# 客服图片上传：单张图片大小上限（字节），默认 10MB
CS_IMAGE_MAX_SIZE = 10 * 1024 * 1024
# 客服视频上传：单个视频大小上限（字节），默认 50MB
CS_VIDEO_MAX_SIZE = 50 * 1024 * 1024
# 客服图片上传：文件存储子目录
CS_IMAGE_UPLOAD_FOLDER = 'chat/images'
# 客服视频上传：文件存储子目录
CS_VIDEO_UPLOAD_FOLDER = 'chat/videos'
# 客服商品搜索：接口最多返回条数
CS_PRODUCT_SEARCH_LIMIT = 50
# 客服一对一：客服回复前用户最多连续发送消息数，超过后提示等待客服回复
CS_USER_MSG_LIMIT_BEFORE_REPLY = 5

# ==================== WebSocket ====================
# 说明：以下配置控制 WebSocket 连接的保活、重连和消息确认机制

# WebSocket 心跳：服务端发送 ping 的间隔（秒）
WS_PING_INTERVAL = 30
# WebSocket 心跳：等待客户端 pong 响应的超时时间（秒）
WS_PONG_TIMEOUT = 10
# WebSocket 心跳：从上次收到 pong 到断开连接的总超时（秒），建议等于 PING_INTERVAL + PONG_TIMEOUT
WS_PING_TOTAL_TIMEOUT = 40
# WebSocket 消息确认：ACK 最大重试次数，超过后标记为发送失败
WS_ACK_MAX_RETRIES = 3
# WebSocket 消息确认：ACK 重试间隔（秒）
WS_ACK_RETRY_DELAY = 5

# ==================== 商品系统（SPU）====================
# 说明：以下配置控制商品管理后台的列表分页、审核流程和媒体限制

# 商品列表：管理后台每页默认显示条数
SPU_ADMIN_DEFAULT_PAGE_SIZE = 20
# 商品审核：组长审核通过后自动上架的延迟时间（分钟），给运营预留操作窗口
SPU_SCHEDULED_PUBLISH_DELAY_MINUTES = 5
# 商品媒体：每个 SPU 最多允许的媒体文件数量（图片+视频合计）
SPU_MEDIA_MAX_COUNT = 6

# ==================== 用户系统 ====================
# 头像上传：允许的文件扩展名白名单
AVATAR_ALLOWED_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.gif', '.webp')

# 单容器内存硬上限（MB），供内存看门狗计算 85% 阈值；与 docker-compose.prod.yml mem_limit 对齐
MEM_LIMIT_MB = int(os.getenv('MEM_LIMIT_MB', '544'))

# R2 上传异步化开关：开启后上传走 Celery（主线程返回 202 + 轮询地址），
# 关闭时保持原同步落盘（返回 200 + url）。默认关闭，待前端对接轮询后再翻 True。
ASYNC_UPLOAD_ENABLED = os.getenv('ASYNC_UPLOAD_ENABLED', 'false').lower() == 'true'

TRUSTED_PROXY_CIDRS = tuple(
    item.strip()
    for item in os.getenv(
        'TRUSTED_PROXY_CIDRS',
        '127.0.0.0/8,::1/128,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16',
    ).split(',')
    if item.strip()
)

# ==================== 操作日志 ====================
# 操作日志文件存储根路径（相对于项目根目录）
OPERATION_LOG_BASE_DIR = os.getenv(
    'OPERATION_LOG_BASE_DIR',
    str(BASE_DIR.parent / 'logs' / 'operations'),
)
# 触发审计日志记录的请求模式（方法:路径前缀），匹配任一即记录审计日志
AUDIT_ACTION_PATTERNS = {'POST:/api/payment/', 'POST:/api/order/', 'DELETE:'}

# ==================== 通知系统 ====================
# 通知列表：默认每页显示条数
NOTIFICATION_DEFAULT_PAGE_SIZE = 20
# 通知列表：缓存过期时间（秒），缓存用户通知列表以减少数据库查询
NOTIFICATION_LIST_CACHE_TTL = 120
# 未读计数：缓存过期时间（秒），缓存用户未读通知数
NOTIFICATION_UNREAD_CACHE_TTL = 60

REFUND_RECONCILIATION_BATCH_SIZE = int(os.getenv('REFUND_RECONCILIATION_BATCH_SIZE', '20'))
# UNKNOWN 退款对账最大重试次数：超过后标记为 FAILED，防止网关持续异常时无限重试（死循环）
REFUND_RECONCILIATION_MAX_ATTEMPTS = int(os.getenv('REFUND_RECONCILIATION_MAX_ATTEMPTS', '5'))

# ==================== 文件存储配置 ====================
# 切换后端: 'local' | 'cos' | 'oss' | 'r2'
FILE_STORAGE = os.getenv('FILE_STORAGE', 'local')
FILE_STORAGE_MAX_SIZE = int(os.getenv('FILE_STORAGE_MAX_SIZE', '10'))
FILE_STORAGE_ALLOWED_TYPES = [
    'image/jpeg', 'image/png', 'image/webp', 'image/gif',
    'video/mp4', 'video/webm',
]

# 腾讯云 COS
COS_SECRET_ID = os.getenv('COS_SECRET_ID', '')
COS_SECRET_KEY = os.getenv('COS_SECRET_KEY', '')
COS_REGION = os.getenv('COS_REGION', 'ap-guangzhou')
COS_BUCKET = os.getenv('COS_BUCKET', '')

# 腾讯云机器翻译（TMT）
# 用于商品名称/描述等内容的自动翻译（如翻译成阿拉伯语）。
# 未配置密钥时翻译接口返回 503，前端可优雅降级（隐藏翻译按钮）。
TMT_SECRET_ID = os.getenv('TMT_SECRET_ID', '')
TMT_SECRET_KEY = os.getenv('TMT_SECRET_KEY', '')
TMT_REGION = os.getenv('TMT_REGION', 'ap-guangzhou')

# 阿里云 OSS
OSS_ACCESS_KEY_ID = os.getenv('OSS_ACCESS_KEY_ID', '')
OSS_ACCESS_KEY_SECRET = os.getenv('OSS_ACCESS_KEY_SECRET', '')
OSS_ENDPOINT = os.getenv('OSS_ENDPOINT', '')
OSS_BUCKET = os.getenv('OSS_BUCKET', '')

# Cloudflare R2
R2_ACCOUNT_ID = os.getenv('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY', '')
R2_BUCKET = os.getenv('R2_BUCKET', '')
R2_PUBLIC_URL = os.getenv('R2_PUBLIC_URL', '')

# ── R2 本地应急磁盘回退 ──────────────────────────────────────────────
# 需求：R2 在本机不可达（断网/未连外网/无凭据）时，读取应回退到本地「pic/」
# 目录下已同步的对象副本，保证开发/离线环境媒体仍可用，且最终 URL 恒以
# pic/ 为前缀。仅当回退启用且本地文件真实存在时才降级，绝不静默伪造实体。
# R2_FALLBACK_ENABLED：总开关，默认开启（本地不可访问时自动套用）；
# LOCAL_FALLBACK_ROOT：备用磁盘目录（写返回路径的物理根），默认指
# MEDIA_ROOT 下的 pic/ 子目录，可通过环境变量/`.env` 覆盖成独立数据卷路径。
R2_FALLBACK_ENABLED = os.getenv('R2_FALLBACK_ENABLED', 'true').lower() == 'true'
LOCAL_FALLBACK_ROOT = os.getenv('LOCAL_FALLBACK_ROOT', '') or ''
# R2 连通性探测后的结果缓存时长（秒）：避免每个请求都反复访问 R2，提升本地回退判定效率。
R2_AVAIL_PROBE_TTL = int(os.getenv('R2_AVAIL_PROBE_TTL', '30'))

# 媒体数量限制（单 SPU：最多 15 张图片 + 3 条视频，超 5 张后图集以滚动方式查看）
MEDIA_MAX_IMAGES_PER_SPU = int(os.getenv('MEDIA_MAX_IMAGES_PER_SPU', '15'))
MEDIA_MAX_VIDEOS_PER_SPU = int(os.getenv('MEDIA_MAX_VIDEOS_PER_SPU', '3'))
# 视频单条大小上限（MB）
MEDIA_MAX_VIDEO_SIZE_MB = int(os.getenv('MEDIA_MAX_VIDEO_SIZE_MB', '200'))
MEDIA_MAX_FILE_SIZE_MB = int(os.getenv('MEDIA_MAX_FILE_SIZE_MB', '10'))

# 图片像素上限（2C4G 内存护栏，务必不要盲目调大）
# ------------------------------------------------------------------
# Pillow 解码一张 W×H 的 RGB 图需要 W*H*3 字节；再经 exif_transpose / convert /
# WebP 编码缓冲，峰值约为原始字节的 3~4 倍：
#   25MP(旧值) → 75MB × 4 ≈ 300MB  ← 生产 web 容器 mem_limit 只有 544m，
#                                    且跑 2 个 gunicorn worker，必被 OOM kill
#   12MP      → 36MB × 4 ≈ 144MB  ← 留出安全余量
# 商品主图实际需求：前端裁剪器最长边封顶 2560，最"高"的预设比例 4:5 → 2560×3200
# ≈ 8.2MP，12MP 完全够用且留有余量。
MEDIA_MAX_IMAGE_PIXELS = int(os.getenv('MEDIA_MAX_IMAGE_PIXELS', '12000000'))

# 批量导入（Excel/zip 导入、import_media_dir 命令）的「软」像素上限。
# 与上面的硬上限不同：超限不拒绝，而是等比缩小后继续导入，
# 保证 DSLR/高像素原图也能进库，同时把单张解码峰值钉死在 ~64MB。
# 默认 16MP 可完整容纳 4000×4000 的商品方图。
MEDIA_IMPORT_MAX_IMAGE_PIXELS = int(os.getenv('MEDIA_IMPORT_MAX_IMAGE_PIXELS', '16000000'))

# 上传临时目录的显式覆盖值（留空则由 dev.py / prod.py 按 MEDIA_ROOT 推导）。
# 注意：base.py 里 MEDIA_ROOT 尚未定义（它在 dev.py / prod.py 中才赋值），
# 所以这里绝不能直接引用 MEDIA_ROOT，否则 settings 导入即 NameError。
MEDIA_UPLOAD_TEMP_DIR = os.getenv('MEDIA_UPLOAD_TEMP_DIR', '')
FILE_UPLOAD_TEMP_DIR = MEDIA_UPLOAD_TEMP_DIR or None


def resolve_upload_temp_dir(media_root: str) -> str:
    """把上传临时目录解析到 media 数据卷内，并返回实际路径（失败返回 ''）。

    >DATA_UPLOAD_MAX_MEMORY_SIZE(默认 2.5MB) 的上传文件会先写到临时目录。
    生产 docker-compose.prod.yml 给 web 挂的是 **tmpfs /tmp:size=32m**，
    而一次商品上传要传 thumb/list/large/original 四个文件（单个最大 10MB），
    2 个 gunicorn worker 并发就能把 32MB 撑爆 → OSError(ENOSPC) → 上传失败。
    这是「存储空间不足」唯一可能字面成立的场景，必须避开 32MB 的 tmpfs。

    放在 media 卷里：容量跟数据盘走，且该卷是容器里少数可写的挂载点
    （web/celery 均为 read_only: true）。
    """
    target = os.getenv('MEDIA_UPLOAD_TEMP_DIR', '') or os.path.join(media_root, '_upload_tmp')
    try:
        os.makedirs(target, exist_ok=True)
        return target
    except OSError:
        # 只读/无权限环境：返回空，由调用方回退到系统临时目录
        return ''

# ==================== 商品缓存 TTL 配置 ====================
GOODS_CACHE_TTL = {
    'CATEGORY_TREE': 3600 * 6,        # 6 小时（几乎不变）
    'BRAND_LIST': 3600 * 12,          # 12 小时
    'SPU_DETAIL': 3600 * 1,           # 1 小时
    'SPU_LIST': 1800,                 # 30 分钟
    'SKU_DETAIL': 1800,               # 30 分钟
    'HOT_PRODUCTS': 300,              # 5 分钟（定时刷新）
    'SPECS_ALL': 3600 * 3,            # 3 小时
    'ATTRIBUTES_BY_CATEGORY': 3600 * 3,  # 3 小时
    'MEDIA_LIST': 1800,               # 30 分钟（媒体列表）
    'SPU_KIND': 3600,                 # 1 小时（商品类型）
}

# ==================== 支付网关配置 ====================
# PayPal
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_CLIENT_SECRET', '')
PAYPAL_WEBHOOK_ID = os.getenv('PAYPAL_WEBHOOK_ID', '')
PAYPAL_BASE_URL = os.getenv('PAYPAL_BASE_URL', 'https://api-m.paypal.com')

# Stripe（信用卡）
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# 支付默认币种
DEFAULT_CURRENCY = os.getenv('DEFAULT_CURRENCY', 'USD')

# 待支付订单有效期（分钟）：超过后允许用户重新发起支付（旧 pending 标记为取消）
PAYMENT_PENDING_TTL_MINUTES = int(os.getenv('PAYMENT_PENDING_TTL_MINUTES', '15'))
# 状态查询节流（秒）：同一支付在间隔内不重复调用网关查询，防 DoS / 防网关限流
PAYMENT_GATEWAY_QUERY_INTERVAL = int(os.getenv('PAYMENT_GATEWAY_QUERY_INTERVAL', '30'))
# 最大待支付时长（分钟）：超过后视为用户放弃，标记为 CANCELLED，避免无限轮询网关（防死循环）
PAYMENT_MAX_PENDING_MINUTES = int(os.getenv('PAYMENT_MAX_PENDING_MINUTES', str(24 * 60)))

# ==================== 订单缓存 TTL 配置 ====================
ORDER_CACHE_TTL = {
    'ORDER_DETAIL': 300,             # 5 分钟
    'ORDER_LIST': 120,               # 2 分钟
}

# ==================== 订单自动任务配置 ====================
ORDER_AUTO_SETTINGS = {
    'CANCEL_UNPAID_MINUTES': 15,     # 未支付订单 15 分钟后自动取消
    'COMPLETE_DELIVERED_DAYS': 7,    # 已签收 7 天后自动完成
}

# ==================== 搜索配置 ====================
SEARCH_SETTINGS = {
    'DEFAULT_PAGE_SIZE': 20,
    'MAX_PAGE_SIZE': 100,
    'SUGGEST_MIN_CHARS': 2,
}

ENVIRONMENT = os.getenv("DJANGO_ENV", "prod")  # 默认开发环境

# ==================== 第三方登录（Social OAuth）配置 ====================
# OAuth 2.0 Client credentials — 在环境变量中设置
SOCIAL_AUTH_GOOGLE_CLIENT_ID = os.getenv('SOCIAL_AUTH_GOOGLE_CLIENT_ID', '')
SOCIAL_AUTH_GOOGLE_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_SECRET', '')

SOCIAL_AUTH_FACEBOOK_APP_ID = os.getenv('SOCIAL_AUTH_FACEBOOK_APP_ID', '')
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv('SOCIAL_AUTH_FACEBOOK_SECRET', '')

SOCIAL_AUTH_LINKEDIN_CLIENT_ID = os.getenv('SOCIAL_AUTH_LINKEDIN_CLIENT_ID', '')
SOCIAL_AUTH_LINKEDIN_SECRET = os.getenv('SOCIAL_AUTH_LINKEDIN_SECRET', '')

# OAuth 回调地址前缀（前端地址）
SOCIAL_AUTH_REDIRECT_BASE = os.getenv('SOCIAL_AUTH_REDIRECT_BASE', 'http://localhost:12700')
