# Generated by Django 5.2.15 on 2026-09-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MediaBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='对象 key')),
                ('content_type', models.CharField(blank=True, default='', max_length=120, verbose_name='内容类型')),
                ('size', models.BigIntegerField(default=0, verbose_name='字节数')),
                ('content', models.BinaryField(verbose_name='内容字节')),
            ],
            options={
                'verbose_name': '媒体回退存储',
                'verbose_name_plural': '媒体回退存储',
                'db_table': 'media_blob',
            },
        ),
    ]