# Generated by Django 5.2.17 on 2026-09-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_sku_code_to_sku_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sku_name',
            field=models.CharField(max_length=100, verbose_name='SKU 名称'),
        ),
    ]
